#!/usr/bin/env bash
# Qwen3.6-27B-FP8 vLLM 启动辅助脚本。
# 注意：当前主流程已改回 vLLM；这个脚本不再走 GGUF/llama.cpp。

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANAGER="$SCRIPT_DIR/manage_cloud_models.sh"
if [[ ! -f "$MANAGER" ]]; then
  echo "找不到管理脚本：$MANAGER" >&2
  exit 1
fi

export QWEN_PORT="${QWEN_PORT:-8010}"
export QWEN_MODEL_PROVIDER="${QWEN_MODEL_PROVIDER:-modelscope}"
export QWEN_MS_MODEL_ID="${QWEN_MS_MODEL_ID:-Qwen/Qwen3.6-27B-FP8}"
export QWEN_MODEL_DIR="${QWEN_MODEL_DIR:-/workspace/modelscope/qwen36_27b_fp8}"
export QWEN_SERVED_MODEL_NAME="${QWEN_SERVED_MODEL_NAME:-qwen3.6-27b-fp8}"
export QWEN_GPU_MEMORY_UTILIZATION="${QWEN_GPU_MEMORY_UTILIZATION:-0.40}"
export QWEN_AUTO_MEMORY_UTIL="${QWEN_AUTO_MEMORY_UTIL:-1}"
export QWEN_MAX_MODEL_LEN="${QWEN_MAX_MODEL_LEN:-32768}"
export QWEN_MAX_NUM_SEQS="${QWEN_MAX_NUM_SEQS:-64}"
export QWEN_MAX_NUM_BATCHED_TOKENS="${QWEN_MAX_NUM_BATCHED_TOKENS:-8192}"
export QWEN_USE_V1="${QWEN_USE_V1:-}"
export QWEN_ENFORCE_EAGER="${QWEN_ENFORCE_EAGER:-1}"
export QWEN_DISABLE_CUDA_GRAPH="${QWEN_DISABLE_CUDA_GRAPH:-1}"
export QWEN_CLEAR_COMPILE_CACHE="${QWEN_CLEAR_COMPILE_CACHE:-1}"
export QWEN_ROCM_SAFE_MODE="${QWEN_ROCM_SAFE_MODE:-1}"
export QWEN_SAFE_MAX_NUM_BATCHED_TOKENS="${QWEN_SAFE_MAX_NUM_BATCHED_TOKENS:-8192}"
export QWEN_LANGUAGE_MODEL_ONLY="${QWEN_LANGUAGE_MODEL_ONLY:-1}"
export QWEN_ENABLE_CHUNKED_PREFILL="${QWEN_ENABLE_CHUNKED_PREFILL:-0}"
export QWEN_ASYNC_SCHEDULING="${QWEN_ASYNC_SCHEDULING:-0}"
export QWEN_DISABLE_ASYNC_OUTPUT_PROC="${QWEN_DISABLE_ASYNC_OUTPUT_PROC:-1}"
export QWEN_PATCH_GDN_WARMUP="${QWEN_PATCH_GDN_WARMUP:-1}"
export QWEN_USE_AITER="${QWEN_USE_AITER:-0}"

cat <<EOF
[Qwen3.6-27B-FP8 vLLM]
QWEN_MODEL_PROVIDER=$QWEN_MODEL_PROVIDER
QWEN_MS_MODEL_ID=$QWEN_MS_MODEL_ID
QWEN_MODEL_DIR=$QWEN_MODEL_DIR
QWEN_PORT=$QWEN_PORT
QWEN_MAX_NUM_SEQS=$QWEN_MAX_NUM_SEQS
QWEN_MAX_MODEL_LEN=$QWEN_MAX_MODEL_LEN
QWEN_GPU_MEMORY_UTILIZATION=$QWEN_GPU_MEMORY_UTILIZATION
QWEN_ROCM_SAFE_MODE=$QWEN_ROCM_SAFE_MODE
QWEN_PATCH_GDN_WARMUP=$QWEN_PATCH_GDN_WARMUP
EOF

case "${1:---restart}" in
  --start|start) exec bash "$MANAGER" start-qwen ;;
  --stop|stop) exec bash "$MANAGER" stop-qwen ;;
  --restart|restart) exec bash "$MANAGER" restart-qwen ;;
  --status|status) exec bash "$MANAGER" status ;;
  --logs|logs) exec bash "$MANAGER" logs-qwen ;;
  *) exec bash "$MANAGER" "$@" ;;
esac
