const state = {status:'accepted', selected:null, selectedSample:null, currentJob:null, pollTimer:null};
const JOB_STORAGE_KEY = 'sydney_current_job_id';
const LAST_JOB_STORAGE_KEY = 'sydney_last_job_id';
function $(id){return document.getElementById(id)}
function scrollToSection(id){$(id)?.scrollIntoView({behavior:'smooth',block:'start'}); if(window.event?.currentTarget?.classList?.contains('navItem')){document.querySelectorAll('.navItem').forEach(x=>x.classList.remove('active')); window.event.currentTarget.classList.add('active')}}
function isActiveJob(job){return job && ['queued','running'].includes(job.status)}
function rememberJob(jobId){state.currentJob=jobId||null; if(jobId){localStorage.setItem(JOB_STORAGE_KEY,jobId)}else{localStorage.removeItem(JOB_STORAGE_KEY)}}
function togglePanel(id){document.getElementById(id)?.classList.toggle('collapsed')}
function toast(msg){const box=document.getElementById('toast'); const d=document.createElement('div'); d.textContent=msg; box.appendChild(d); setTimeout(()=>d.remove(),5200)}
async function api(path, opts={}){const res=await fetch(path,{headers:{'Content-Type':'application/json'},...opts}); const txt=await res.text(); let data={}; try{data=txt?JSON.parse(txt):{}}catch(e){data={raw:txt}} if(!res.ok) throw new Error(data.detail||data.error||txt||res.statusText); return data}
function endpoint(prefix){return {base_url:document.getElementById(prefix+'Base').value.trim(), api_key:document.getElementById(prefix+'Key').value.trim(), model:document.getElementById(prefix+'Model').value.trim(), api_protocol:document.getElementById(prefix+'Protocol').value}}
function firstReadyAuxEndpoint(){for(const p of ['translator','simulator','judge']){const ep=endpoint(p); if(ep.base_url&&ep.model) return {prefix:p, endpoint:ep}} return {prefix:'translator', endpoint:endpoint('translator')}}
function effectiveEndpoint(prefix){if(sameAuxModel.checked && ['simulator','translator','judge'].includes(prefix)){return firstReadyAuxEndpoint().endpoint} return endpoint(prefix)}
function syncAuxUi(){if(sameAuxModel.checked){const shared=firstReadyAuxEndpoint(); toast('已启用共用强模型：'+(shared?.prefix||'translator'))}}
function applyDefaults(d){if(!d) return; count.value=d.count??5; concurrency.value=d.concurrency??3; maxTurns.value=d.max_turns??12; translateToZh.checked=!!d.translate_to_zh; sameAuxModel.checked=!!d.same_aux_model; useJudge.checked=!!d.use_judge; if(d.target_model_key) targetModel.value=d.target_model_key; if(d.train_mode) trainMode.value=d.train_mode; includeReview.checked=!!d.include_needs_review; onlyDistill.checked=d.only_dialogue_distillation!==false; if(d.source_prompt_mode==='legacy_chat'&&teacherProtocol) teacherProtocol.value='legacy_chat_completions'}
async function loadConfig(){try{const c=await api('/api/config'); teacherBase.value=c.teacher.base_url||''; teacherModel.value=c.teacher.model||''; teacherProtocol.value=c.teacher.api_protocol||'responses'; simulatorBase.value=c.simulator?.base_url||''; simulatorModel.value=c.simulator?.model||''; simulatorProtocol.value=c.simulator?.api_protocol||'responses'; translatorBase.value=c.translator?.base_url||''; translatorModel.value=c.translator?.model||''; translatorProtocol.value=c.translator?.api_protocol||'responses'; judgeBase.value=c.judge.base_url||''; judgeModel.value=c.judge.model||''; judgeProtocol.value=c.judge.api_protocol||'responses'; applyDefaults(c.defaults); if(c.teacher.has_key) teacherKey.placeholder='已从 .env 读取，可留空'; if(c.simulator?.has_key) simulatorKey.placeholder='已从 .env 读取，可留空'; if(c.translator?.has_key) translatorKey.placeholder='已从 .env 读取，可留空'; if(c.judge.has_key) judgeKey.placeholder='已从 .env 读取，可留空'}catch(e){toast('读取配置失败：'+e.message)}}
async function loadStats(){const s=await api('/api/stats'); stTotal.textContent=s.total||0; stAccepted.textContent=s.by_status?.accepted?.count||0; stReview.textContent=s.by_status?.needs_review?.count||0; stRejected.textContent=s.by_status?.rejected?.count||0}
function setStatus(st){state.status=st; document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.status===st)); loadSamples()}
async function loadSamples(){await loadStats(); const q=encodeURIComponent(search.value.trim()); const data=await api(`/api/samples?status=${state.status}&q=${q}&limit=80`); const list=sampleList; list.innerHTML=''; if(!data.items.length){list.innerHTML='<div class="hint" style="padding:20px">没有样本。先点击生成。</div>'; return} data.items.forEach(item=>{const el=document.createElement('div'); el.className='card'+(state.selected===item.id?' active':''); el.onclick=()=>selectSample(item.id); const tags=(item.tags||[]).slice(0,5).map(t=>`<span class="badge">${escapeHtml(t)}</span>`).join(''); el.innerHTML=`<div class="cardTop"><b>${escapeHtml(item.theme||'Untitled')}</b><span class="score">${Number(item.score).toFixed(1)}</span></div><div>${tags}</div><div class="preview">${escapeHtml(item.preview||'')}</div><div class="meta" style="margin-top:8px">${item.status} · ${escapeHtml(item.id)}</div>`; list.appendChild(el)})}
async function selectSample(id){state.selected=id; const s=await api('/api/samples/'+id); state.selectedSample=s; sampleId.textContent=s.id; editStatus.value=s.status; editScore.value=s.score; jsonEdit.value=JSON.stringify(s.messages,null,2); renderChat(s); renderReasons(s); await loadSamples(); scrollToSection('reviewPanel')}
function addBubble(container, role, text, extra=''){const b=document.createElement('div'); b.className='bubble '+role+(extra?' '+extra:''); b.textContent=text; container.appendChild(b); container.scrollTop=container.scrollHeight}
function clearLiveChat(){liveChat.innerHTML='<div class="liveEmpty"><div><div class="emptyIcon">💬</div><b>等待新的对话生成</b><div class="hint" style="margin-top:8px">点击“生成 + 审核”后，这里会实时展示 Human / Sydney 聊天气泡。</div></div></div>'}
function renderLiveEvents(job){const events=(job.logs||[]).slice(-260); liveChat.innerHTML=''; let visible=0; events.forEach(ev=>{if(ev.kind==='chat'){addBubble(liveChat, ev.role==='user'?'user':'assistant', ev.message); visible++}else if(ev.level==='error'){addBubble(liveChat,'event',`[${ev.time||''}] ${ev.message}`,'error'); visible++}else if(ev.level==='warn'||ev.kind==='warn'){addBubble(liveChat,'event',`[${ev.time||''}] ${ev.message}`,'warn'); visible++}else if(ev.message&&(/任务启动|开始|翻译完成|审核完成|已保存|任务完成|生成失败|丢弃|重复|accepted|rejected|needs_review/.test(ev.message))){addBubble(liveChat,'event',`[${ev.time||''}] ${ev.message}`); visible++}}); if(!visible) clearLiveChat()}
function renderChat(s){chat.innerHTML=''; s.messages.forEach(m=>{addBubble(chat,m.role,(m.role==='system'?'SYSTEM\n':'')+m.content)}); const src=s.metadata?.source_messages_en; if(Array.isArray(src)&&src.length){const details=document.createElement('details'); details.className='bubble system'; const summary=document.createElement('summary'); summary.textContent='查看英文源对话 metadata.source_messages_en'; details.appendChild(summary); const pre=document.createElement('pre'); pre.className='meta'; pre.textContent=JSON.stringify(src,null,2); details.appendChild(pre); chat.appendChild(details)}}
function renderReasons(s){const r=s.review||{}; const reasons=r.reasons||[]; reviewReasons.innerHTML=`<div class="reason">overall: ${Number(r.overall||s.score||0).toFixed(2)} · reviewer: ${escapeHtml(r.reviewer||'')}</div>`+reasons.map(x=>`<div class="reason">${escapeHtml(x)}</div>`).join('')+`<pre class="meta">${escapeHtml(JSON.stringify(r.scores||{},null,2))}</pre>`}
async function saveSample(){if(!state.selected) return toast('未选择样本'); let messages; try{messages=JSON.parse(jsonEdit.value)}catch(e){return toast('messages JSON 不合法：'+e.message)} await api('/api/samples/'+state.selected,{method:'PUT',body:JSON.stringify({messages,status:editStatus.value,score:Number(editScore.value)})}); toast('已保存'); await selectSample(state.selected); await loadStats()}
async function quickReject(){if(!state.selected) return; editStatus.value='rejected'; editScore.value=Math.min(Number(editScore.value||0),4); await saveSample()}
async function testTeacher(){try{const res=await api('/api/config/test',{method:'POST',body:JSON.stringify({endpoint:endpoint('teacher'),prefix:'TEACHER'})}); toast(res.ok?'Sydney/source OK':'Sydney/source 失败：'+res.error)}catch(e){toast('测试失败：'+e.message)}}
async function testSimulator(){try{const ep=effectiveEndpoint('simulator'); const res=await api('/api/config/test',{method:'POST',body:JSON.stringify({endpoint:ep,prefix:'SIMULATOR'})}); toast(res.ok?'Human Simulator OK':'Human Simulator 失败：'+res.error)}catch(e){toast('测试失败：'+e.message)}}
async function testTranslator(){try{const ep=effectiveEndpoint('translator'); const res=await api('/api/config/test',{method:'POST',body:JSON.stringify({endpoint:ep,prefix:'TRANSLATOR'})}); toast(res.ok?'Translator OK':'Translator 失败：'+res.error)}catch(e){toast('测试失败：'+e.message)}}
function renderJob(job){jobPanel.style.display='block'; const total=Number(job.total||0); const done=Number(job.completed||0); const pct=job.progress?job.progress.percent:(total?Math.round(done*1000/total)/10:0); jobStatus.textContent=`${job.status} · ${done}/${total}`; if($('jobPercent')) $('jobPercent').textContent=`${pct}%`; if($('topStatus')) $('topStatus').textContent=isActiveJob(job)?'generating':(job.status||'ready'); jobBar.style.width=`${Math.max(0,Math.min(100,pct))}%`; if($('sideProgress')) $('sideProgress').style.width=`${Math.max(4,Math.min(100,pct||4))}%`; const trans=job.translate_to_zh?'en→zh':'en only'; const translator=job.translator?.enabled?job.translator.model:'disabled'; const shared=job.same_aux_model?` · shared ${job.shared_aux_source||'on'}`:''; jobCounts.textContent=`accepted ${job.accepted||0} · review ${job.needs_review||0} · rejected ${job.rejected||0} · failed ${job.failed||0} · concurrency ${job.concurrency||0} · ${trans} · translator ${translator}${shared}`; renderLiveEvents(job)}
async function pollJob(jobId){try{const job=await api('/api/jobs/'+jobId); renderJob(job); await loadStats(); if(!isActiveJob(job)){if(state.pollTimer) clearInterval(state.pollTimer); state.pollTimer=null; if(state.currentJob===jobId){rememberJob(null); localStorage.setItem(LAST_JOB_STORAGE_KEY,jobId)} genBtn.disabled=false; genBtn.innerHTML='生成 + 审核'; toast(job.status==='completed'?'生成任务完成':job.status==='interrupted'?'任务被服务重启中断':'生成任务失败'); await loadSamples()}else{genBtn.disabled=true; genBtn.innerHTML='<span class="spinner"></span> 生成中'}}catch(e){if(state.pollTimer) clearInterval(state.pollTimer); state.pollTimer=null; rememberJob(null); genBtn.disabled=false; genBtn.innerHTML='生成 + 审核'; toast('轮询任务失败：'+e.message)}}
async function startPolling(jobId, showToast=false){rememberJob(jobId); if(state.pollTimer) clearInterval(state.pollTimer); genBtn.disabled=true; genBtn.innerHTML='<span class="spinner"></span> 生成中'; state.pollTimer=setInterval(()=>pollJob(jobId),1000); await pollJob(jobId); if(showToast) toast('已恢复任务进度：'+jobId.slice(0,8))}
async function resumeJob(){let jobId=localStorage.getItem(JOB_STORAGE_KEY); if(jobId){try{const job=await api('/api/jobs/'+jobId); renderJob(job); if(isActiveJob(job)){await startPolling(jobId,true); return}else{rememberJob(null); localStorage.setItem(LAST_JOB_STORAGE_KEY,jobId)}}catch(e){rememberJob(null)}} try{const active=await api('/api/jobs?active=true&limit=1'); if(active.items&&active.items.length){await startPolling(active.items[0].id,true); return}}catch(e){} try{const lastId=localStorage.getItem(LAST_JOB_STORAGE_KEY); const latest=lastId?await api('/api/jobs/'+lastId).catch(()=>null):(await api('/api/jobs?limit=1')).items?.[0]; if(latest){renderJob(latest)}}catch(e){}}
async function generate(){const btn=genBtn; btn.disabled=true; btn.innerHTML='<span class="spinner"></span> 生成中'; clearLiveChat(); try{const seedVal=seed.value.trim(); const data=await api('/api/generate',{method:'POST',body:JSON.stringify({count:Number(count.value||5),concurrency:Number(concurrency.value||3),max_turns:Number(maxTurns.value||12),translate_to_zh:translateToZh.checked,same_aux_model:sameAuxModel.checked,teacher:endpoint('teacher'),simulator:endpoint('simulator'),translator:endpoint('translator'),judge:endpoint('judge'),use_judge:useJudge.checked,seed:seedVal?Number(seedVal):null})}); renderJob(data.job); toast('任务已启动：'+data.job_id.slice(0,8)); await startPolling(data.job_id,false); scrollToSection('livePanel')}catch(e){toast('生成启动失败：'+e.message); rememberJob(null); btn.disabled=false; btn.innerHTML='生成 + 审核'}}
async function exportData(){try{const data=await api('/api/export',{method:'POST',body:JSON.stringify({target_model_key:targetModel.value,train_mode:trainMode.value,include_needs_review:includeReview.checked,only_dialogue_distillation:onlyDistill.checked})}); exportLinks.innerHTML=`导出 ${data.count} 条：<a href="${data.files.chatml}">train_chatml.jsonl</a><a href="${data.files.sharegpt}">train_sharegpt.jsonl</a><a href="${data.files.notebook}">train_sydney.ipynb</a>`; toast('导出完成')}catch(e){toast('导出失败：'+e.message)}}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
loadConfig().then(()=>loadSamples()).then(loadStats).then(resumeJob);
